packaging_format = 2

id = "forgejo-pages-server"
name = "Pages Server for Forgejo"
description.en = "The Codeberg Pages Server – with custom domain support, per-repo pages using the \"pages\" branch, caching and much more! Easy to selfhost too!"
description.ru = "Сервер страниц для Forgejo - с поддержкой персонализированных доменов, страницы для каждого репозитория с помощью ветки «pages», кеширование и многое другое!"

version = "0.1~ynh2"

maintainers = ["alexAubin"]

[upstream]
license = "WTFPL"

[integration]
yunohost = ">= 11.1"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "1M"
ram.build = "1M"
ram.runtime = "1M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/helloworld"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
