#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chown -R $app:$app "$install_dir"
chmod +x "$install_dir/pages-server"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding systemd configuration for $app..." --weight=1

# Create a dedicated systemd config
ynh_add_systemd_config

yunohost service add $app --description="Forgejo Pages Server" --log="/var/log/$app/$app.log"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding configuration files..." --weight=1

# Create an environment file
cat >> .env << EOF
# ACME Settings
ACME_ACCEPT_TERMS=$acme_use
ACME_EMAIL="$acme_email"

# DNS Provider Settings
DNS_PROVIDER="$dns_provider"
NO_DNS_01="$dns_use"
$dns_credentials

# Forge Settings
GITEA_API_TOKEN="$forgejo_token"
GITEA_ROOT="$forgejo_url"

# Domain Settings
PAGES_DOMAIN="$domain"
RAW_DOMAIN="$domain_raw"
EOF

#=================================================
# GENERIC FINALIZATION
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
